export const content_type = [
  "magazine",
  "book",
  "documentary",
  "events",
  "podcast",
  "video",
  "article",
  "blog",
  "course",
  "eBook",
  "exercise",
  "software tool",
  "documentation",
  "cheatsheet",
  "diagram",
  "reference",
  "youtube channel",
  "organisation",
  "other",
];

export const mark_stage = [
  "Week 1: Workflows",
  "Week 2: Typescript and code quality",
  "Week 3: React, HTML and CSS",
  "Week 4: React and event handlers",
  "Week 5: React and useEffect",
  "Week 7: NodeJs and Express",
  "Week 8: SQL and persistence",
  "Week 10+: Full stack projects",
];

export const recommendation_type = [
  "I recommend this resource after having used it",
  "I do not recommend this resource, having used it",
  "I haven't used this resource but it looks promising",
];

export const tags = [
  "React",
  "Javascript",
  "Typescript",
  "MERN",
  "Express",
  "Git",
  "PERN",
  "CSS",
  "HTML",
  "Deploying",
  "Heroku",
  "Jest",
  "Testing",
  "Cypress",
  "Event Handlers",
  "useState",
  "useEffect",
  "Databases",
  "SQL",
  "Projects",
];
